# Generated by Django 6.0.3 on 2026-06-19 20:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_subtotal_alter_order_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo')], max_length=20, verbose_name='Tipo de Descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del Descuento')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Compra Mínima')),
                ('max_uses', models.PositiveIntegerField(default=0, verbose_name='Usos Máximos (0 = ilimitado)')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Veces Usado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Válido Desde')),
                ('valid_to', models.DateTimeField(verbose_name='Válido Hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('defective', 'Producto defectuoso'), ('wrong_item', 'Producto incorrecto'), ('size_issue', 'Problema de talla'), ('not_as_described', 'No coincide con la descripción'), ('changed_mind', 'Cambio de opinión'), ('other', 'Otro')], max_length=20, verbose_name='Motivo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('approved', 'Aprobado'), ('received', 'Recibido'), ('refunded', 'Reembolsado'), ('rejected', 'Rechazado')], default='requested', max_length=20, verbose_name='Estado')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto a Reembolsar')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del Administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='orders.orderitem', verbose_name='Artículos a Devolver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
