# Generated by Django 6.0.3 on 2026-03-28 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('gender', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('U', 'Unisex'), ('K', 'Niños')], default='U', max_length=1)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Oferta')),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='Imagen Principal')),
                ('sizes', models.CharField(default='S,M,L', max_length=200, verbose_name='Tallas Disponibles (separadas por coma)')),
                ('colors', models.CharField(default='Negro,Blanco', max_length=200, verbose_name='Colores (separados por coma)')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Material')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('out_of_stock', 'Sin Stock')], default='active', max_length=20, verbose_name='Estado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto Alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['order'],
            },
        ),
    ]
